=== 112KA/x-repository-template/schemas/pages.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <!-- Root element -->
  <xs:element name="pages">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="page" type="pageType" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="version" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>

  <!-- Page type definition -->
  <xs:complexType name="pageType">
    <xs:sequence>
      <!-- Multi-view pages -->
      <xs:element name="view" type="viewType" minOccurs="0" maxOccurs="unbounded"/>
      <!-- External navigation buttons -->
      <xs:element name="button" type="buttonType" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="id" type="xs:string" use="required"/>
    <xs:attribute name="url" type="xs:string" use="required"/>
    <xs:attribute name="title" type="xs:string"/>
    <xs:attribute name="defaultView" type="xs:string"/>
    <xs:attribute name="viewTransition" type="xs:string" default="fade"/>
  </xs:complexType>

  <!-- View type definition (for multi-view pages) -->
  <xs:complexType name="viewType">
    <xs:sequence>
      <xs:element name="button" type="buttonType" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="id" type="xs:string" use="required"/>
    <xs:attribute name="name" type="xs:string" use="required"/>
    <xs:attribute name="title" type="xs:string"/>
  </xs:complexType>

  <!-- Button type definition -->
  <xs:complexType name="buttonType">
    <xs:sequence>
      <xs:element name="label" type="xs:string"/>
    </xs:sequence>
    <xs:attribute name="action" type="xs:string"/>
    <xs:attribute name="href" type="xs:string"/>
  </xs:complexType>
</xs:schema>

=== 112KA/x-repository-template/apps/app-nextjs/definitions/pages.xml
<?xml version="1.0" encoding="UTF-8"?>
<pages version="1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="../../schemas/pages.xsd">
  <page>
    <url>/examples/page-mockup/</url>
    <button>
      <label>Page1</label>
      <href>/examples/page-mockup/page1/</href>
    </button>
    <button>
      <label>Page2</label>
      <href>/examples/page-mockup/page2/</href>
    </button>
  </page>
  <page>
    <url>/examples/page-mockup/page1/</url>
    <button>
      <label>Back</label>
      <href>../</href>
    </button>
  </page>
  <page>
    <url>/examples/page-mockup/page2/</url>
    <button>
      <label>Back</label>
      <href>../</href>
    </button>
  </page>
</pages>

=== 112KA/x-repository-template/apps/app-nextjs/definitions/pages/definition.xml
<?xml version="1.0" encoding="UTF-8"?>
<pages version="1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="../../schemas/pages.xsd">

  <!-- Test Transitions page with multi-view and external pages -->
  <page id="test-transitions" url="/examples/test-transitions/" title="Test Transitions index">
    <views default="view-1" transition="fade">
      <view id="view-1" title="View 1">
        <button label="Go to View 2" action="to:view-2"/>
        <button label="Page 1" href="page1/"/>
        <button label="Page 2" href="page2/"/>
      </view>
      
      <view id="view-2" title="View 2">
        <button label="Back to View 1" action="to:view-1"/>
      </view>
    </views>
  </page>

  <!-- Test Transitions sub-pages for external navigation -->
  <page id="test-transitions-page1" url="/examples/test-transitions/page1/" title="Test Transitions Page 1">
    <button label="Page 2" href="./page2/"/>
    <button label="Back" href="../"/>
  </page>
  
  <page id="test-transitions-page2" url="/examples/test-transitions/page2/" title="Test Transitions Page 2">
    <button label="Page 1" href="./page1/"/>
    <button label="Back" href="../"/>
  </page>
</pages>
